<?php
// This script scans image directories and generates JavaScript files with the list of images
// Processes: slideshow, introImage, portfolioImage, workImage (excludes favicon)

// Directories to scan and their corresponding JS files
$directories = [
    'images/slideshow/' => 'slideshow-images.js',
    'images/introImage/' => 'intro-images.js',
    'images/portfolioImage/' => 'portfolio-images.js',
    'images/workImage/' => 'work-images.js'
];

// Allowed image extensions
$allowed_extensions = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'JPG', 'JPEG', 'PNG', 'GIF', 'WEBP'];

// Function to get images from a directory
function getImagesFromDirectory($directory, $allowed_extensions) {
    $images = [];

    if (is_dir($directory)) {
        if ($handle = opendir($directory)) {
            while (($file = readdir($handle)) !== false) {
                // Skip . and .. directories
                if ($file == '.' || $file == '..') {
                    continue;
                }

                // Check if the file has an allowed extension
                $extension = pathinfo($file, PATHINFO_EXTENSION);
                if (in_array($extension, $allowed_extensions)) {
                    $images[] = $directory . $file;
                }
            }
            closedir($handle);
        }
    }

    return $images;
}

// Function to generate JavaScript content
function generateJSContent($images, $variableName) {
    $js_content = "// This file is automatically generated by generate-slideshow-list.php\n";
    $js_content .= "// Do not edit this file directly\n\n";
    $js_content .= "const " . $variableName . " = [\n";

    foreach ($images as $image) {
        $js_content .= "    '" . $image . "',\n";
    }

    $js_content .= "];\n";

    return $js_content;
}

// Process each directory
$totalImages = 0;
foreach ($directories as $directory => $jsFile) {
    $images = getImagesFromDirectory($directory, $allowed_extensions);

    // Generate variable name based on directory
    $dirName = basename(rtrim($directory, '/'));

    // Create clean variable names
    $variableNames = [
        'slideshow' => 'slideshowImages',
        'introImage' => 'introImages',
        'portfolioImage' => 'portfolioImages',
        'workImage' => 'workImages'
    ];

    $variableName = isset($variableNames[$dirName]) ? $variableNames[$dirName] : $dirName . 'Images';

    // Generate JavaScript content
    $js_content = generateJSContent($images, $variableName);

    // Write to JavaScript file
    file_put_contents($jsFile, $js_content);

    echo "Generated " . $jsFile . " with " . count($images) . " images from " . $directory . "\n";
    $totalImages += count($images);
}

echo "\nAll image lists generated successfully!\n";
echo "Total images processed: " . $totalImages . "\n";
echo "Generated files: " . implode(', ', array_values($directories)) . "\n";
?>
