// This file is automatically generated by generate-slideshow-list.php
// Do not edit this file directly

const slideshowImages = [
    'images/slideshow/IMG_0834.jpg',
    'images/slideshow/testPic.jpg',
];
