// This file is automatically generated by generate-slideshow-list.php
// Do not edit this file directly

const slideshowImages = [
    'images/slideshow/DJI_0076.jpg',
    'images/slideshow/DJI_0272.jpg',
    'images/slideshow/DJI_0321.jpg',
    'images/slideshow/DJI_0376.jpg',
    'images/slideshow/DJI_0414.jpg',
    'images/slideshow/DJI_0430.jpg',
    'images/slideshow/DJI_0479.jpg',
    'images/slideshow/DJI_0550.jpg',
    'images/slideshow/DJI_0564.jpg',
    'images/slideshow/DJI_0625.jpg',
    'images/slideshow/DJI_0706.jpg',
    'images/slideshow/DSC_2656.jpg',
];
