// This file is automatically generated by generate-slideshow-list.php
// Do not edit this file directly

const slideshowImages = [
    'images/slideshow/DJI_0076.JPG',
    'images/slideshow/DJI_0272.JPG',
    'images/slideshow/DJI_0321.JPG',
    'images/slideshow/DJI_0376.JPG',
    'images/slideshow/DJI_0414.JPG',
    'images/slideshow/DJI_0430.JPG',
    'images/slideshow/DJI_0479.JPG',
    'images/slideshow/DJI_0550.JPG',
    'images/slideshow/DJI_0564.JPG',
    'images/slideshow/DJI_0625.JPG',
    'images/slideshow/DJI_0706.JPG',
    'images/slideshow/DSC_2656.JPG',
];
